tool_to_extinguish = "sing a#song";
text = [
    global.player.mabel ? "MY, WHAT AN ANGELIC SOUND!&I'VE TRULY ASCENDED TO HEAVEN!" : "WELL, THAT WAS CERTAINLY...#SOMETHING.",
    "WHO KNEW MUSICAL NOTES COULD #EXTINGUISH FLAMES?",
    "BESIDES, OF COURSE, SCIENTISTS, #SOUND ENGINEERS, COMMON FOLK...",
    "...WELL, THAT SINGING BRINGS US #RIGHT TO TODAY'S SPONSOR: #@FF1B2DOPERA DX@FFFFFF!",
    "YOU MAY BE FAMILIAR WITH @FF1B2DOPERA@FFFFFF, #THE CHROMIUM-BASED ART FORM",
    "WHERE A STORY IS TOLD THROUGH #SINGING.",
    "WELL, GOOD NEWS!",
    "THE TEAM BEHIND @FF1B2DOPERA@FFFFFF HAS DEV-#ELOPED A NEW, SPECIALIZED ART #FORM SPECIFICALLY FOR GAMERS!",
    "@FFFFFF@FF1B2DOPERA DX@FFFFFF, OR @FF1B2DOPERA DELUXE@FFFFFF, #IS A BRAND NEW WAY TO ENJOY #OPERA--`YOUR PREFERRED WAY!",
    "WITH @FF1B2DOPERA DX@FFFFFF, YOU CAN SET #LIMITS ON VARIOUS SYSTEM RE-#SOURCES, LIKE VOLUME AND PITCH.",
    "THIS FREES UP YOUR EARS WHILE #YOU PERFORM OTHER, MORE IMPOR-#TANT TASKS, LIKE PODCASTS!",
    "I'M SURE WE'VE ALL HAD THE #EXPERIENCE VISITING AN OPERA,",
    "WHEN THE LADY HITS THAT REALLY #HIGH NOTE THAT MAKES YOUR EARS #AND HEAD RING.",
    "WELL, WITH @FF1B2DOPERA DX@FFFFFF, YOU CAN #FILTER THOSE OUT WHILE ENJOYING #THE REST OF THE PERFORMANCE!",
    "OH, BUT THAT'S NOT ALL!&EVER HAD TROUBLE UNDERSTANDING #THE LYRICS?",
    "@FFFFFF@FF1B2DOPERA DX@FFFFFF COMES WITH NATIVE #@7289daCONCORD@FFFFFF INTEGRATION, LETTING #YOU TRANSLATE AS YOU GO!",
    "OF COURSE, THIS IS A GEOMETRIC #TRANSLATION, SO YOU STILL WON'T #UNDERSTAND IT,",
    "BUT YOU'LL TRULY SEE IT #DIFFERENTLY--`FROM A WHOLE #DIFFERENT PERSPECTIVE!",
    "SO START USING @FF1B2DOPERA DX@FFFFFF TODAY!&YOUR EARS `(AND YOUR NEIGHBORS)` #WILL THANK YOU FOR IT!",
    "NOW, BACK TO OUR VOCAL HERO!"
];
