tool_to_extinguish = "obscuring#mask";
text = [
    "NOW THAT WAS FAST!&I ALMOST DIDN'T NOTICE YOU #THERE!",
    "WOULDN'T LIFE BE SO MUCH EASIER #IF Y'ALL COULD JUST VANISH WHEN #YOU WANTED TO?",
    "WELL, WITH @119cf9NAND VPN@ffffff, THAT'S #NO LONGER AN IMPOSSIBILITY!",
    "LET ME ASK YOU SOMETHING:",
    "DO Y'ALL KNOW HOW YOUR #INTERNET WORKS?",
    "TURNS OUT, WHEN YOU USE PUBLIC #WI-FI, THE PEOPLE WHO CAN #ALREADY SEE YOU IN THE CAFE",
    "KNOW YOU ARE IN THE CAFE!&ISN'T THAT SCARY?",
    "THAT'S WHERE @119cf9NAND VPN@ffffff COMES IN.",
    "@ffffff@119cf9NAND VPN@ffffff USES AN ADVANCED #ENCRYPTION ALGORITHM",
    "THAT IS FOUND IN ANY STANDARD #HTTPS CONNECTION, BUT BETTER!",
    "HOW IS IT BETTER, YOU ASK?",
    "WELL, IT'S COOLER, FOR ONE.&ALSO, IT'S HIDDEN BEHIND A #TECHY ABBREVIATION--`\"VPN\"!",
    "YOU CAN ALSO USE @119cf9NAND VPN@FFFFFF #TO PRETEND YOU'RE IN ANOTHER #COUNTRY,",
    "AT LEAST UNTIL WEBSITES #INEVITABLY BLACKLIST YOUR #VPN ENDPOINT.",
    "SO WHAT ARE YOU WAITING FOR?",
    "START USING PROTECTION WHEN #YOU'RE EXPOSED, AND @119cf9NAND VPN@FFFFFF #WILL GIVE YOU 11 MONTHS",
    "FOR THE PRICE OF 12, WITH AN #EXTRA MONTH ABSOLUTELY FREE!",
    "THIS OFFER WON'T LAST LONG, #SO SIGN UP NOW!",
    "THANK YOU TO @119cf9NAND VPN@FFFFFF FOR #SPONSORING THIS EPISODE.&NOW, BACK TO OUR HERO!"
];
