tool_to_extinguish = "April#showers";
text = [
    global.player.mabel ? "AIN'T SHE A GENIUS, FOLKS?" : "WE HAVE A TRUE GENIUS AMONG US, #FOLKS!",
    "WHO ELSE COULD HAVE PREDICTED #THAT SIMPLE WATER COULD #EXTINGUISH A FIRE?",
    "SPEAKING OF WATER, I'D LIKE TO #TAKE A MOMENT TO THANK TODAY'S #SPONSOR, @BD652DRAIN: SHOWER LEGENDS@FFFFFF!",
    "@FFFFFF@BD652DRAIN: SHOWER LEGENDS@FFFFFF IS THE #MOST AMBITIOUS INTRAPERSONAL AC-#TIVITY EVER TO HIT THE MARKET!",
    "I'VE BEEN @BD652DSHOWERING@FFFFFF IN MY FREE #TIME, AND I'M GENUINELY #ADDICTED.",
    "WHAT'S REALLY AWESOME ABOUT #@BD652DSHOWERING@FFFFFF IS THAT THE GRAPHICS #ARE SIMPLY DAZZLING!",
    "I MEAN, JUST LOOK AT THOSE #REALISTIC WATER PHYSICS!&I'M IN COMPLETE AWE!",
    "IN @BD652DRAIN@FFFFFF, YOU CAN RANK UP #WITHOUT THE HASSLE OF LONGSOME #BATHS OR INTENSE STENCHES!",
    "Course, the people who play #this kind of game are probably #used to the stench by now...",
    "OH, BUT NOW IS THE ABSOLUTE #BEST TIME TO START!",
    "FOR A LIMITED TIME ONLY, YOU #CAN GET AN EXCLUSIVE STARTER #PACK CONTAINING",
    "THE FEATURED GIDEON PIN SOAP, #ALONG WITH A FREE LEGENDARY #SHOWER HEAD,",
    "5 EXTRA BARS OF SOAP, #AND OVER 20 GALLONS OF WATER!",
    "SO WHAT ARE YOU WAITING FOR?",
    "ABANDON YOUR BASEMENT-DWELLER #@C79B3BLEAGUE OF SHOWER LEGENDS",
    "AND TRY OUT A REAL GAME FOR #REAL GAMERS, MADE FOR MOBILE!",
    "THIS OFFER WON'T LAST LONG, #SO SIGN UP NOW!",
    "THANK YOU TO @BD652DRAIN: SHOWER #LEGENDS@FFFFFF FOR SPONSORING THIS #EPISODE.",
    "NOW, BACK TO OUR SCENTSIBLE #HERO!"
];
