global.inventory = [
    ITEM_NAME.LOSER_CANDY,
    ITEM_NAME.ONION_15,
    ITEM_NAME.ONION_15,
    ITEM_NAME.SPAGHETTI,
    ITEM_NAME.ONION_15,
    ITEM_NAME.ONION_15,
    ITEM_NAME.ONION_MAX,
    ITEM_NAME.PIZZA_INFINITE,
    ITEM_NAME.COOKIE_JAR_FULL,
    ITEM_NAME.COOKIE_JAR_FULL,
    ITEM_NAME.COOKIE_JAR_FULL,
    ITEM_NAME.COOKIE_JAR_FULL,
    ITEM_NAME.COOKIE_JAR_FULL,
    ITEM_NAME.SPAGHETTI,
    ITEM_NAME.NONE,
    ITEM_NAME.NONE
]