/// @desc Consumes an item in `global.inventory` that corresponds with a local inventory (as generated by `scr_get_inventory`).
/// Note that this does **not** remove the item from the `_local_inventory`.
/// @param {Array<Enum.ITEM_INDEX>} _local_inventory A compressed inventory as generated by `scr_get_inventory`, corresponding to `global.inventory`'s non-`NONE` entries
/// @param {Real} _local_index The index in the `_local_inventory` that is being removed from `global.inventory`
/// @param {Enum.ITEM_INDEX|Undefined} _force_new If not `undefined`, this will override the removed item's `useResult`
function scr_remove_local_item(_local_inventory, _local_index, _force_new = undefined)
{
    var _global_index = -1;
    for (var i = 0; i <= _local_index; ++i)
    {
        _global_index = scr_select_array(global.inventory, function(_global_item) {return _global_item != ITEM_INDEX.NONE;}, false, _global_index);
    }
    var _success = true;
    var _item_name = _local_inventory[_local_index];
    if (_global_index < 0 || _global_index >= array_length(global.inventory) || global.inventory[_global_index] != _item_name)
    {
        show_debug_message($"Failed to register global inventory; got {_global_index} from {global.inventory}");
        _success = false;
        _global_index = array_get_index(global.inventory, _item_name);
    }
    var _item = global.ITEM_INFO[_item_name];
    global.inventory[_global_index] = is_undefined(_force_new) ? _item.useResult : _force_new;
    return _success;
}
