text = [
	"GREETINGS, SUBJECT, AND #WELCOME TO THE FIRST #TEST.",
	"MY PUZZLES ARE UNLIKE #ANYTHING YOU HAVE EVER #SEEN BEFORE!",
	"UNLESS, I SUPPOSE, YOU HAVE #PLAYED A CERTAIN GAME #SIMILAR TO...",
	"OF COURSE, I'M TALKING #ABOUT THE HIT CLASSIC OF #2015...",
	"UNDERDUNGEONS, #UNDERDUNGEONS, AND MORE #UNDERDUNGEONS.",
	"TURN ALL THE TRIANGLES #INTO CIRCLES!",
	"IF YOU MAKE THEM SQUARES, #THE PUZZLE IS LOST.",
	"BUT NOT TO WORRY!&I HAVE INSTALLED A FAIL #SAFE!",
	"HIT THAT LEVER NEXT TO #THIS SIGN TO RESET THE #PUZZLE.",
	"GOOD LUCK, SUBJECT."
]
for(var i = 0; i < array_length(text); i++) font[i] = fnt_papyrus_gui