draw_set_font(fnt_battle)
draw_text(30,403,global.player[player.name]+"  LV "+string(global.player[player.lv]))
draw_sprite(spr_hpkr,0,250,405)
draw_healthbar(280,400,300+(4*global.player[player.lv]),420,100*(global.player[player.hp]/global.player[player.maxhp]),c_red,c_yellow,c_yellow,0,true,false)
draw_text(315+(4*global.player[player.lv]),403,string(global.player[player.hp])+" / "+string(global.player[player.maxhp]))
