text = [
	"SOME \"ROCKS\" (PATENT #PENDING) CAN BE MOVED, IF #THEY ARE SMALL ENOUGH.",
	"HOWEVER, MOVING ROCKS IS #AGAINST THE RULES, SO #PLEASE DO NOT DO THAT.",
	"IF YOU EVER NEED, #JUST WALK UP TO ONE AND #PRESS @FFFF00Z@FFFFFF (OR @FFFF00ENTER@FFFFFF).",
	"THE NATURAL LAWS OF #PHYSICS PREVENT THEM FROM #MOVING MORE THAN ONCE,",
	"SO PLAN ACCORDINGLY.",
	"ALSO REMEMBER THAT THEY #CAN'T BE MOVED WHERE #YOU CAN'T MOVE.",
	"IF YOU MAKE A MISTAKE, #YOU CAN RESET THE ROCKS #WITH THE PUZZLE LEVER."
]
font = [fnt_papyrus_gui,fnt_papyrus_gui,fnt_papyrus_gui,fnt_papyrus_gui,fnt_papyrus_gui,fnt_papyrus_gui,fnt_papyrus_gui]